### ISSUE TITLE
readfolder function returns random number of files/folders inside

### ISSUE THREAD

**Issue by segvan** [dekyfin/RichFilemanager-NODE#1]
The problem is inside getIndividualFileInfo function. Because $index in case of assync calls are not sorted, so in any moment callback fuction could be called. 

function getIndividualFileInfo(pp, files, loopInfo, callback, $index) {
		parsePath(paths.posix.join(pp.uiPath, files[$index]), (ipp) => {
			console.log($index);
			getinfo(ipp, (result) => {
				loopInfo.results.push(result);
				if ($index + 1 >= loopInfo.total) {
					callback(loopInfo.results);
				} // if
			}); // getinfo
		}); // parsePath
	} // getIndividualFileInfo

Proposed solution: to change condition to
 if (loopInfo.results.length === loopInfo.total) {

In such case function works reliably.

**Comment by dekyfin** [comment]
Thanks for your contribution. I will work on it shortly. I would be glad if you could create a pull request for future issues. Thanks once again
