### ISSUE TITLE
starting node

### ISSUE THREAD

**Issue by tim-moody** [dekyfin/RichFilemanager-NODE#3]
What is the relationship between RichFilemanager/connectors/nodejs/filemanager.js and 
RichFilemanager/node_modules/rich-filemanager-node/ (from this repo)?

They seem to be versions of the same thing. I have done:
in filemanager.config.json
change to 
	    "api": {
	        "lang": "nodejs",
	        "connectorUrl": "http://localhost:9000/",
in RichFilemanager/node_modules/rich-filemanager-node/ index.js
change var config = "/library/www/html/RichFilemanager/config/filemanager.config.json";
node rich-filemanager-node/ index.js runs for a second and terminates with no error message

How do I start the node connector?

**Comment by tim-moody** [comment]
needed to add separate node app to use filemanager.

**Comment by hathemi** [comment]
how did you run rich-filemanager using nodejs connector on you browser ??

**Comment by hathemi** [comment]
@tim-moody  what do i need to add to start the node connector? i still can't figure out a solution to launch filemanager in my browser.
